export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_ENV_HINTS=1
export HOMEBREW_BUNDLE_FILE=$HOME/.config/homebrew/Brewfile

if [ -f ~/.secrets ]; then
    source ~/.secrets
fi

fpath=($HOMEBREW_PREFIX/share/zsh/site-functions $fpath)

autoload -Uz compinit
compinit

if [ "$(which uv)" = "/opt/homebrew/bin/uv" ]; then
    eval "$(uv generate-shell-completion zsh)"
fi

if [ "$(which uv)" = "/opt/homebrew/bin/uv" ]; then
    eval "$(uvx --generate-shell-completion zsh)"
fi

if [ -f $(brew --prefix)/opt/spaceship/spaceship.zsh ]; then
    source $(brew --prefix)/opt/spaceship/spaceship.zsh
fi
